/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.RoleController;
import Controllers.UsuarioController;
import java.util.HashMap;

/**
 *
 * @author 000093883
 */
public class InsertUsuarioView extends javax.swing.JFrame {
    
    private HashMap<String, Integer> list;
    

    /**
     * Creates new form InsertUsuarioView
     */
    public InsertUsuarioView() {
        initComponents();
        getRoles();
        this.Role.setBorder(null);
    }
    
    public final void getRoles(){
        list = new RoleController().getRoles();
        list.forEach((x, y)->{
            this.Role.addItem(x);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new rojeru_san.RSButton();
        jLabel6 = new javax.swing.JLabel();
        Role = new javax.swing.JComboBox<>();
        Pass1 = new rojeru_san.RSMPassView();
        Email = new rojeru_san.RSMTextFull();
        Pass2 = new rojeru_san.RSMPassView();
        Nombre = new rojeru_san.RSMTextFull();
        Telefono = new rojeru_san.RSMTextFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rol:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 470, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 470, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 470, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 324, 470, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 430, 470, -1));

        Guardar.setBackground(new java.awt.Color(3, 218, 198));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar-el-archivo.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setColorText(new java.awt.Color(0, 0, 0));
        Guardar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 470, 56));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 26)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Repita la contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 460, -1));

        Role.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Role.setMaximumRowCount(3);
        Role.setBorder(null);
        Role.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 270, 50));

        Pass1.setForeground(new java.awt.Color(0, 0, 0));
        Pass1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Pass1.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Pass1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Pass1.setPlaceholder("");
        Pass1.setSelectedTextColor(new java.awt.Color(102, 153, 255));
        jPanel1.add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 350, 50));

        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Email.setBotonColor(new java.awt.Color(98, 0, 238));
        Email.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Email.setPlaceholder("");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 350, 50));

        Pass2.setForeground(new java.awt.Color(0, 0, 0));
        Pass2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Pass2.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Pass2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Pass2.setPlaceholder("");
        Pass2.setSelectedTextColor(new java.awt.Color(102, 153, 255));
        jPanel1.add(Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 350, 50));

        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Nombre.setBotonColor(new java.awt.Color(98, 0, 238));
        Nombre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Nombre.setPlaceholder("");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 350, 50));

        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Telefono.setBotonColor(new java.awt.Color(98, 0, 238));
        Telefono.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Telefono.setPlaceholder("");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        UsuarioController user = new UsuarioController();
        user.insertUser(new Object[]{
            Nombre.getText(),
            Email.getText(),
            Telefono.getText(), 
            Pass1.getText(),
            (int)list.get(Role.getSelectedItem().toString())
        });
        this.dispose();
    }//GEN-LAST:event_GuardarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSMTextFull Email;
    private rojeru_san.RSButton Guardar;
    private rojeru_san.RSMTextFull Nombre;
    private rojeru_san.RSMPassView Pass1;
    private rojeru_san.RSMPassView Pass2;
    private javax.swing.JComboBox<String> Role;
    private rojeru_san.RSMTextFull Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
