/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Views.CustomView.CustomDialog;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author 000093883
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Inicio de sesión");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelIconos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelInformacion = new javax.swing.JPanel();
        LabelPassword = new javax.swing.JLabel();
        IconoCorreo = new javax.swing.JLabel();
        IconoCandado = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        botonPanel = new javax.swing.JPanel();
        labelBotonIngresar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Correo = new LIB.FSTexFieldMD();
        fSPasswordFieldMD1 = new LIB.FSPasswordFieldMD();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIconos.setBackground(new java.awt.Color(98, 0, 238));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 31)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO DE NUEVO");

        javax.swing.GroupLayout PanelIconosLayout = new javax.swing.GroupLayout(PanelIconos);
        PanelIconos.setLayout(PanelIconosLayout);
        PanelIconosLayout.setHorizontalGroup(
            PanelIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIconosLayout.createSequentialGroup()
                .addGroup(PanelIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIconosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIconosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelIconosLayout.setVerticalGroup(
            PanelIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIconosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jPanel1.add(PanelIconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 630));

        PanelInformacion.setBackground(new java.awt.Color(255, 255, 255));
        PanelInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelPassword.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        LabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPassword.setText("Contraseña:");
        PanelInformacion.add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 360, 57));

        IconoCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arroba.png"))); // NOI18N
        IconoCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelInformacion.add(IconoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 50));

        IconoCandado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconoCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/candado.png"))); // NOI18N
        PanelInformacion.add(IconoCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 57));

        labelCorreo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCorreo.setText("Correo electronico:");
        PanelInformacion.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, 369, 57));

        botonPanel.setBackground(new java.awt.Color(3, 218, 198));
        botonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBotonIngresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelBotonIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBotonIngresar.setText("INGRESAR");
        labelBotonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBotonIngresarMouseClicked(evt);
            }
        });
        botonPanel.add(labelBotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        PanelInformacion.add(botonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 60));

        jPanel2.setBackground(new java.awt.Color(255, 222, 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("OLVIDO CONTRASEÑA");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        PanelInformacion.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 200, 60));

        Correo.setForeground(new java.awt.Color(0, 0, 0));
        Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Correo.setBordeColorFocus(new java.awt.Color(55, 0, 179));
        Correo.setBordeColorNoFocus(new java.awt.Color(255, 255, 255));
        Correo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Correo.setPlaceholder("ejemplo@ejemplo.com");
        PanelInformacion.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 320, 60));

        fSPasswordFieldMD1.setForeground(new java.awt.Color(0, 0, 0));
        fSPasswordFieldMD1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fSPasswordFieldMD1.setBordeColorFocus(new java.awt.Color(55, 0, 179));
        fSPasswordFieldMD1.setBordeColorNoFocus(new java.awt.Color(255, 255, 255));
        fSPasswordFieldMD1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fSPasswordFieldMD1.setPlaceholder("");
        PanelInformacion.add(fSPasswordFieldMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 320, 60));

        jPanel1.add(PanelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 440, 630));

        jMenu1.setText("Usuarios");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar-contacto.png"))); // NOI18N
        jMenuItem1.setText("Registrar usuario");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelBotonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBotonIngresarMouseClicked
        JDialog dialog = new CustomDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_labelBotonIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSTexFieldMD Correo;
    private javax.swing.JLabel IconoCandado;
    private javax.swing.JLabel IconoCorreo;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JPanel PanelIconos;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel botonPanel;
    private LIB.FSPasswordFieldMD fSPasswordFieldMD1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBotonIngresar;
    private javax.swing.JLabel labelCorreo;
    // End of variables declaration//GEN-END:variables
}
