/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ColoniaController;
import Controllers.TareaController;
import Controllers.UsuarioController;
import Models.UsuarioModel;
import Views.CustomView.CustomDialog;
import java.util.Date;
import java.util.HashMap;

/**
 *
 * @author 000093883
 */
public class TareaView extends javax.swing.JFrame {
    
    private HashMap<String, Integer> map = new TareaController().getTareasMap();
    private HashMap<String, Integer> listColonia = new ColoniaController().getColoniasMap();
    private HashMap<String, Integer> mapEncargados = new UsuarioController().getAdminUsersMap();
    private UsuarioModel user = new UsuarioModel();
    /**
     * Creates new form TareaView
     */
    public TareaView() {
        initComponents();
        setValues();
    }
    
    public TareaView(UsuarioModel user) {
        initComponents();
        setValues();
        this.user = user;
    }
    
    private void setValues(){
        this.TareaAsignacion.removeAllItems();
        this.ColoniaCreacion.removeAllItems();
        this.EncargadoAsignacion.removeAllItems();
        map.forEach((x, y) ->{
            this.TareaAsignacion.addItem(x);
        });
        listColonia.forEach((x,y) ->{
            this.ColoniaCreacion.addItem(x);
        });
        mapEncargados.forEach((x, y) -> {
            this.EncargadoAsignacion.addItem(x);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Salir = new rojeru_san.RSButton();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Descripcion = new LIB.FSTexFieldMD();
        jLabel4 = new javax.swing.JLabel();
        ColoniaCreacion = new javax.swing.JComboBox<>();
        GuardarCreacion = new rojeru_san.RSButton();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TareaAsignacion = new javax.swing.JComboBox<>();
        EncargadoAsignacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        GuardarAsignacion = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 0, 238));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cubeta.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        Salir.setBackground(new java.awt.Color(3, 218, 197));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar-sesion.png"))); // NOI18N
        Salir.setText("Salir");
        Salir.setColorText(new java.awt.Color(0, 0, 0));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear nueva tarea");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descripción:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, -1));

        Descripcion.setForeground(new java.awt.Color(0, 0, 0));
        Descripcion.setBordeColorFocus(new java.awt.Color(0, 112, 192));
        Descripcion.setBordeColorNoFocus(new java.awt.Color(0, 0, 0));
        Descripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Descripcion.setPlaceholder("");
        jPanel3.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 380, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Colonia:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, -1));

        ColoniaCreacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel3.add(ColoniaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 380, 50));

        GuardarCreacion.setBackground(new java.awt.Color(3, 218, 197));
        GuardarCreacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar-el-archivo.png"))); // NOI18N
        GuardarCreacion.setText("Guardar");
        GuardarCreacion.setColorText(new java.awt.Color(0, 0, 0));
        GuardarCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCreacionActionPerformed(evt);
            }
        });
        jPanel3.add(GuardarCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 400, -1));

        rSPanelShadow1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 430, 570));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Asignar tareas");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seleccione una tarea:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, -1));

        TareaAsignacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel4.add(TareaAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 380, 50));

        EncargadoAsignacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel4.add(EncargadoAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 380, 50));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Seleccione encargado:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, -1));

        GuardarAsignacion.setBackground(new java.awt.Color(3, 218, 197));
        GuardarAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar-el-archivo.png"))); // NOI18N
        GuardarAsignacion.setText("Guardar");
        GuardarAsignacion.setColorText(new java.awt.Color(0, 0, 0));
        GuardarAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarAsignacionActionPerformed(evt);
            }
        });
        jPanel4.add(GuardarAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 400, -1));

        rSPanelShadow2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 430, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCreacionActionPerformed
        Object[] data = new Object[]{
            Descripcion.getText(),
            (Date)new Date(),
            "Creada",
            (int)listColonia.get(ColoniaCreacion.getSelectedItem().toString())
        };
        new TareaController().insertTareas(data);
        map = new TareaController().getTareasMap();
        listColonia = new ColoniaController().getColoniasMap();
        setValues();
        new CustomDialog(this, true, "OK", "Tarea creada correctamente", 1).setVisible(true);
        this.Descripcion.setText("");
    }//GEN-LAST:event_GuardarCreacionActionPerformed

    private void GuardarAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarAsignacionActionPerformed
        Object[] data = new Object[]{
            (int)map.get(TareaAsignacion.getSelectedItem().toString()),
            (int)mapEncargados.get(EncargadoAsignacion.getSelectedItem().toString()),
            (Date) new Date()
        };
        new TareaController().insertAsignacionTareas(user.getUserID(), data);
        new CustomDialog(this, true, "OK", "Tarea asignada correctamente", 1).setVisible(true);
    }//GEN-LAST:event_GuardarAsignacionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColoniaCreacion;
    private LIB.FSTexFieldMD Descripcion;
    private javax.swing.JComboBox<String> EncargadoAsignacion;
    private rojeru_san.RSButton GuardarAsignacion;
    private rojeru_san.RSButton GuardarCreacion;
    private rojeru_san.RSButton Salir;
    private javax.swing.JComboBox<String> TareaAsignacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    // End of variables declaration//GEN-END:variables
}
