/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.TareaController;
import Models.TableModels.TareasPendientesTableModel;
import Models.TareaModel;
import Models.UsuarioModel;
import java.util.List;

/**
 *
 * @author 000093883
 */
public class UserView extends javax.swing.JFrame {
    
    private UsuarioModel user;

    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public UserView(UsuarioModel user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.user = user;
        getTareasPendientes();
        this.Nombre.setText("Nombre: " + this.user.getNombre());
        this.Correo.setText("Correo: " + this.user.getEmail());
        this.Telefono.setText("Telefono: " + this.user.getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        VerTareas = new rojeru_san.RSButton();
        jLabel1 = new javax.swing.JLabel();
        Recargar = new rojeru_san.RSButton();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tareas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 0, 238));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerTareas.setBackground(new java.awt.Color(3, 218, 197));
        VerTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar-sesion.png"))); // NOI18N
        VerTareas.setText("Cerrar");
        VerTareas.setColorText(new java.awt.Color(0, 0, 0));
        jPanel2.add(VerTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 240, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cubeta.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        Recargar.setBackground(new java.awt.Color(3, 218, 197));
        Recargar.setForeground(new java.awt.Color(0, 0, 0));
        Recargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/recargar.png"))); // NOI18N
        Recargar.setText("Recargar información");
        Recargar.setColorText(new java.awt.Color(0, 0, 0));
        Recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargarActionPerformed(evt);
            }
        });
        jPanel2.add(Recargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 32)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información del usuario");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Nombre.setText("Nombre: Gerardo Cárcamo");
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, -1));

        Correo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Correo.setText("Correo: gerca4401@gmail.com");
        jPanel3.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 420, -1));

        Telefono.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Telefono.setText("Telefono: 8443832692");
        jPanel3.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 420, -1));

        rSPanelShadow1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 440, 570));

        Tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tareas);

        rSPanelShadow2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 420, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecargarActionPerformed
        getTareasPendientes();
    }//GEN-LAST:event_RecargarActionPerformed

    void getTareasPendientes(){
        List<TareaModel> list = new TareaController().getTareasAsignadas(user.getUserID());
        TareasPendientesTableModel modelo = new TareasPendientesTableModel(list);
        Tareas.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Nombre;
    private rojeru_san.RSButton Recargar;
    private javax.swing.JTable Tareas;
    private javax.swing.JLabel Telefono;
    private rojeru_san.RSButton VerTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    // End of variables declaration//GEN-END:variables
}
